# -*- coding: utf-8 -*-
"""bingo v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEX8CqPUUQKjEETsHdUCCECCONj80ocU
"""

import random

class CartelaObserver:
    def __init__(self, cartela):
        self.cartela = cartela

    def verificar_cartela_cheia(self):
        return all(numero["marcado"] for numero in self.cartela)


class Bingo:
    def __init__(self):
        self.numeros_sorteados = set()
        self.cartelas_observers = []

    def registrar_cartela(self, observer):
        self.cartelas_observers.append(observer)

    def sortear_bola(self):
        while True:
            numero = random.randint(1, 75)
            if numero not in self.numeros_sorteados:
                self.numeros_sorteados.add(numero)
                print(f"Número sorteado: {numero}")
                return numero

    def notificar_observers(self):
        for observer in self.cartelas_observers:
            if observer.verificar_cartela_cheia():
                print("A cartela está completa! Bingo!")
                return True
        return False


def criar_cartela():
    cartela = []
    colunas = {
        "B": range(1, 16),
        "I": range(16, 31),
        "N": range(31, 46),
        "G": range(46, 61),
        "O": range(61, 76),
    }

    for coluna, intervalo in colunas.items():
        numeros = random.sample(intervalo, 5 if coluna != "N" else 5)
        cartela.extend([{"numero": num, "marcado": False} for num in numeros])

    return cartela

def exibir_cartela(cartela):
    print("\nCartela:")
    print(" B  |  I  |  N  |  G  |  O  ")
    for i in range(5):
        linha = []
        for j in range(5):
            index = i * 5 + j
            if i == 2 and j == 2:
                linha.append(" X ")
            elif index < len(cartela):
                if cartela[index]['marcado']:
                    linha.append(" X  ")
                else:
                    linha.append(f" {cartela[index]['numero']:2d} ")
            else:
                 pass
        print(" | ".join(linha))
    print()

def jogar_bingo():
    bingo = Bingo()
    cartela = criar_cartela()
    observer = CartelaObserver(cartela)
    bingo.registrar_cartela(observer)

    cartela_original = cartela[:]
    exibir_cartela(cartela_original)

    while True:
        numero = bingo.sortear_bola()

        cartela = cartela_original[:]
        for item in cartela:
            if item["numero"] == numero:
                item["marcado"] = True
                break

        exibir_cartela(cartela)

        if bingo.notificar_observers():
            break

    exibir_cartela(cartela)


if __name__ == "__main__":
    jogar_bingo()